# Generated by Django 4.2.9 on 2024-05-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='people',
            field=models.IntegerField(),
        ),
    ]
