# Generated by Django 4.2.9 on 2024-05-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_reservations_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='people',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='space',
            field=models.CharField(choices=[['A', 'A'], ['B', 'B'], ['C', 'C'], ['D', 'D']], default='A', max_length=1),
        ),
    ]
