# Generated by Django 4.2.9 on 2024-05-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_reservations_people_alter_reservations_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='space',
            field=models.CharField(choices=[['A', 'A'], ['B', 'B'], ['C', 'C'], ['D', 'D']], default='A', max_length=2),
        ),
    ]
