# Generated by Django 4.2.9 on 2024-05-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_reservations_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='id',
            field=models.CharField(default='151IY1MT03', max_length=10, primary_key=True, serialize=False),
        ),
    ]
