# Generated by Django 4.2.9 on 2024-05-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_reservations_date_alter_reservations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='id',
            field=models.CharField(default='4171F86HJ2', max_length=10, primary_key=True, serialize=False),
        ),
    ]
