# Generated by Django 4.2.9 on 2024-05-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_reservations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='id',
            field=models.CharField(default='NK39945339', max_length=10, primary_key=True, serialize=False),
        ),
    ]
