# Generated by Django 4.2.9 on 2024-06-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_alter_reservations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='id',
            field=models.CharField(default='FQ732U0722', max_length=10, primary_key=True, serialize=False),
        ),
    ]
