# Generated by Django 4.2.9 on 2024-05-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(default='CAT', max_length=200),
        ),
    ]
